/** ไอคอนทั้งหน้า — lucide-react (iconLibrary ของ shadcn) ผ่านชื่อเดียว; คอมโพเนนต์ shadcn ใหม่ import ไอคอนจาก lucide-react ตรงได้ */
import type { LucideIcon, LucideProps } from 'lucide-react';
import {
  BadgeCheckIcon,
  CopyIcon,
  DownloadIcon,
  EyeIcon,
  EyeOffIcon,
  GripVerticalIcon,
  ImageIcon,
  LayersIcon,
  LinkIcon,
  LockIcon,
  PanelLeftIcon,
  PrinterIcon,
  ReceiptIcon,
  RefreshCwIcon,
  ArrowLeftRightIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronUpIcon,
  ChevronsUpDownIcon,
  HexagonIcon,
  MoonIcon,
  PlusIcon,
  SunIcon,
  XIcon,
  SettingsIcon,
  ShieldCheckIcon,
  TagIcon,
  Trash2Icon,
  TriangleAlertIcon,
  UploadIcon,
  UserIcon,
} from 'lucide-react';

const ICONS = {
  user: UserIcon,
  copy: CopyIcon,
  checkCheck: BadgeCheckIcon,
  layers: LayersIcon,
  lock: LockIcon,
  trash: Trash2Icon,
  upload: UploadIcon,
  settings: SettingsIcon,
  refresh: RefreshCwIcon,
  alert: TriangleAlertIcon,
  grip: GripVerticalIcon,
  swap: ArrowLeftRightIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  panelLeft: PanelLeftIcon,
  sun: SunIcon,
  moon: MoonIcon,
  hexagon: HexagonIcon,
  plus: PlusIcon,
  x: XIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronUp: ChevronUpIcon,
  chevronsUpDown: ChevronsUpDownIcon,
  check: CheckIcon,
  receipt: ReceiptIcon,
  download: DownloadIcon,
  image: ImageIcon,
  printer: PrinterIcon,
  link: LinkIcon,
  tag: TagIcon,
  shield: ShieldCheckIcon,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, ...rest }: { name: IconName } & LucideProps) {
  const C = ICONS[name];
  return <C aria-hidden="true" {...rest} />;
}
